"""
Adversarial tests for the semantic cache (`SemanticCache`).

Goal: characterize *which* categories of input the cache will falsely match,
and ship that table in the repo so users can see the real trade-offs of
their threshold choice.

Two execution modes:

1. **Default (no env var):** the live test is skipped. Only the mocked
   regression test runs (verifies the cosine-similarity logic is wired
   correctly without touching a real embedding API).

2. **`THRIFTAI_LIVE_TEST=1` + an embedding-provider key:** every pair is
   embedded against the chosen model, similarity recorded, and the
   results are written to `tests/adversarial_report.md` as a markdown
   table. Positive controls are asserted; wrong-hit hazards are
   *measured* but not asserted (the report is the deliverable).

To regenerate the report:

```
OPENAI_API_KEY=… THRIFTAI_LIVE_TEST=1 \
  pytest tests/test_adversarial.py -m live
```

Override the embedding model with `THRIFTAI_EMBED_MODEL=…` if needed.
"""

from __future__ import annotations

import os
from pathlib import Path
from unittest.mock import MagicMock, patch

import numpy as np
import pytest

from thriftai.cache.semantic import SemanticCache, _cosine_similarity
from tests.adversarial_pairs import ADVERSARIAL_PAIRS


LIVE = os.environ.get("THRIFTAI_LIVE_TEST") == "1"
EMBED_MODEL = os.environ.get("THRIFTAI_EMBED_MODEL", "text-embedding-3-small")
REPORT_PATH = Path(__file__).parent / "adversarial_report.md"
THRESHOLDS = (0.85, 0.92, 0.95)


# ---------------------------------------------------------------------------
# Result accumulator + report writer
# ---------------------------------------------------------------------------


_results: list[dict] = []


@pytest.fixture(scope="session", autouse=True)
def _emit_report():
    """At end of session, regenerate adversarial_report.md if we ran live."""
    yield
    if LIVE and _results:
        REPORT_PATH.write_text(_render_report(_results))


def _verdict_cell(should_match: bool | None, sim: float, threshold: float) -> str:
    above = sim >= threshold
    if should_match is True:
        return "HIT ✓" if above else "MISS ✗"   # ✗ = positive control failed
    if should_match is False:
        return "HIT ✗" if above else "MISS ✓"   # ✗ = wrong-hit hazard
    return "HIT" if above else "MISS"           # gray area, no judgement


def _render_report(results: list[dict]) -> str:
    lines = [
        f"# Adversarial cache pairs (`{EMBED_MODEL}`)",
        "",
        "Generated by `THRIFTAI_LIVE_TEST=1 pytest tests/test_adversarial.py`.",
        "",
        "**Reading the table:**",
        "- `HIT ✓` — the cache correctly served a paraphrase response (positive control).",
        "- `HIT ✗` — the cache **would have served the wrong response** (wrong-hit hazard).",
        "- `MISS ✓` — the threshold correctly rejected a distinct query.",
        "- `MISS ✗` — the threshold rejected a legitimate paraphrase (false miss).",
        "",
        "Tune the `semantic_threshold` setting on `Session` based on which "
        "row of the @-columns matches your tolerance.",
        "",
        "| # | Category | Sim | @0.85 | @0.92 | @0.95 | Notes |",
        "|---|---|---:|---|---|---|---|",
    ]
    for i, r in enumerate(results, 1):
        sim = r["sim"]
        cells = [_verdict_cell(r["should_match"], sim, t) for t in THRESHOLDS]
        lines.append(
            f"| {i} | `{r['category']}` | {sim:.3f} | "
            f"{cells[0]} | {cells[1]} | {cells[2]} | {r['notes']} |"
        )
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Live adversarial test (gated)
# ---------------------------------------------------------------------------


@pytest.mark.live
@pytest.mark.skipif(
    not LIVE,
    reason="set THRIFTAI_LIVE_TEST=1 (and an embedding API key) to run",
)
@pytest.mark.parametrize(
    "category,query_a,query_b,should_match,notes",
    ADVERSARIAL_PAIRS,
    ids=[p[0] for p in ADVERSARIAL_PAIRS],
)
def test_pair_similarity_live(
    tmp_path_factory, category, query_a, query_b, should_match, notes
):
    """Embed both queries, record cosine similarity, assert positive controls."""
    cache = SemanticCache(
        db_path=tmp_path_factory.mktemp("sem") / "cache.db",
        embedding_model=EMBED_MODEL,
        threshold=0.92,
    )
    va = cache.embed([{"role": "user", "content": query_a}])
    vb = cache.embed([{"role": "user", "content": query_b}])
    sim = _cosine_similarity(va, vb)
    _results.append({
        "category": category,
        "sim": sim,
        "should_match": should_match,
        "notes": notes,
    })
    if should_match is True:
        # Positive control: paraphrases must score above the default threshold,
        # otherwise the cache loses its core value proposition.
        assert sim >= 0.92, (
            f"positive control '{category}' failed: sim={sim:.3f} "
            f"(query_a={query_a!r}, query_b={query_b!r})"
        )


# ---------------------------------------------------------------------------
# Mocked regression — runs in CI, no key required
# ---------------------------------------------------------------------------


def test_threshold_logic_is_wired_correctly(tmp_path):
    """Sanity: with controlled vectors the cache hits above threshold and
    misses below. Confirms our cosine + threshold plumbing — no real API."""
    cache = SemanticCache(
        db_path=tmp_path / "cache.db",
        embedding_model="mock",
        threshold=0.92,
    )

    base = np.ones(8, dtype=np.float32)
    near = base + np.full(8, 0.01, dtype=np.float32)        # very similar
    far = np.array([1, -1, 1, -1, 1, -1, 1, -1], dtype=np.float32)  # nearly orthogonal

    def scripted_embed(*args, **kwargs):
        text = (kwargs.get("input") or args[1])[0]
        vector = {"a": base, "a-paraphrase": near, "z": far}[text]
        resp = MagicMock()
        resp.data = [{"embedding": vector.tolist()}]
        return resp

    with patch("litellm.embedding", side_effect=scripted_embed), \
         patch("litellm.completion_cost", return_value=0.0):
        cache.put(
            agent_name="ag", prompt_hash="p", content_hash="c1",
            messages=[{"role": "user", "content": "a"}],
            model="m", response_text="OK", input_tokens=1, output_tokens=1,
        )
        # Near-identical → HIT
        hit = cache.get(
            agent_name="ag", prompt_hash="p",
            messages=[{"role": "user", "content": "a-paraphrase"}],
        )
        assert hit is not None
        assert hit["response_text"] == "OK"
        # Distant → MISS
        miss = cache.get(
            agent_name="ag", prompt_hash="p",
            messages=[{"role": "user", "content": "z"}],
        )
        assert miss is None


def test_verdict_cell_table_logic():
    """The HIT/MISS markers in the report are unambiguous in all 6 cases."""
    # Positive control: above threshold → HIT ✓, below → MISS ✗
    assert _verdict_cell(True, 0.95, 0.92) == "HIT ✓"
    assert _verdict_cell(True, 0.80, 0.92) == "MISS ✗"
    # Wrong-hit hazard: above threshold → HIT ✗, below → MISS ✓
    assert _verdict_cell(False, 0.95, 0.92) == "HIT ✗"
    assert _verdict_cell(False, 0.80, 0.92) == "MISS ✓"
    # Gray area: neutral
    assert _verdict_cell(None, 0.95, 0.92) == "HIT"
    assert _verdict_cell(None, 0.80, 0.92) == "MISS"
